name: Angular PR CI
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: NX Setup
        shell: bash
        run: |
          if [[ $GITHUB_BASE_REF ]]
          then
            export NX_BASE=remotes/origin/$GITHUB_BASE_REF
          else
            export NX_BASE=$(git rev-parse HEAD~1)
          fi
          echo "Base => $NX_BASE"
          echo "NX_BASE=$NX_BASE" >> $GITHUB_ENV

      # Setup
      - name: Install Dependencies
        run: npm ci --loglevel=error
      - name: Build DevKit
        run: npm run build:devkit

        # Test
      # - name: Lint affected files
      #   run: npm run affected:lint -- --base=$NX_BASE --parallel
      - name: Check formatting
        run: npm run format:check -- --base=$NX_BASE --parallel
      - name: Run affected unit tests
        run: npm run affected:test -- --base=$NX_BASE --parallel

        # Angular build
      - name: Build Test App
        run: npm run build -- --prod
      - name: Build Angular Theme
        run: npm run build angular-theme -- --prod
      - name: Build Angular Components
        run: npm run build angular-components
      - name: Upload Angular Theme Artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: 'angular-theme'
          path: './themes/angular-theme'
      - name: Upload Angular Components Artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: 'angular-components'
          path: './dist/libs/angular-components'
        # Deploy
      - name: Deploy angular test app to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './dist/apps/angular-test-app'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy angular app from GitHub Actions'
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          alias: deploy-preview-${{ github.event.number }}
          github-deployment-environment: angular-pr
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
